### ISSUE TITLE
Newly created notes do not get cursor focus

### ISSUE THREAD

**Issue by tallguyjenks** [dobrovolsky/obsidian-structure#8]
Like this plugin, the dot hierarchies from dendron were one of the things I loved most about it!

For this issue, to replicate: 

1. run command `Structured Plugin: Create New Note`
2. new note generated in a new pane
3. original pane still has cursor focus

replicated in HELP vault with on other plugins or customizations

**Comment by tgrosinger** [comment]
I think ideally it would not open the new node in a new pane unless the current pane is pinned.
